# Generated by Django 2.2.7 on 2019-11-05 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_powerbank.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=200, verbose_name='user agent')),
                ('ts', models.DateTimeField(auto_now=True, verbose_name='time stamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='visitor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Recipient email address', max_length=254, verbose_name='email')),
                ('secret', django_powerbank.db.models.fields.SecretField(help_text='Autogenerated password for the shared data', max_length=20, verbose_name='secret')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('access_counter', models.SmallIntegerField(default=0)),
                ('url', models.URLField(blank=True, help_text='Url to share', null=True, verbose_name='url')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='visitor')),
            ],
            options={
                'verbose_name': 'shared url',
                'verbose_name_plural': 'shared url',
                'default_related_name': 'shared_urls',
            },
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Recipient email address', max_length=254, verbose_name='email')),
                ('secret', django_powerbank.db.models.fields.SecretField(help_text='Autogenerated password for the shared data', max_length=20, verbose_name='secret')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('access_counter', models.SmallIntegerField(default=0)),
                ('file', models.FileField(blank=True, help_text='File to share', null=True, upload_to='', verbose_name='file')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='visitor')),
            ],
            options={
                'verbose_name': 'shared file',
                'verbose_name_plural': 'shared file',
                'default_related_name': 'shared_files',
            },
        ),
    ]
